name: Wildgoat-API CI

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload FTP
      uses: sebastianpopp/ftp-action@v1.0.0
      with: 
        host: ${{ secrets.SERVER }}
        user: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        localDir: "api"
        remoteDir: "www/api"